#!/usr/bin/env bash
set -e

# List repositories
repos=$(find . -name ".git" -maxdepth 2 | sed 's/^\.\/\(.*\)\/\.git$/\1/')

error=0
while read -r repo; do

    cd ${repo}
    git remote prune origin
    cd ..

done <<< "$repos"

exit $error
